#ifndef RL_WORLD_UNIT_H
#define RL_WORLD_UNIT_H

#include <cstdint>
#include <memory>
#include <type_traits>
#include <string>

#include "Rl.World/PreRegister.h"

namespace rl
{

/** Compressed representation of unit face curvature for GPU transfer */
class MappedUnitShapeCurve final
{
                uint32_t polyCurvePlanes; /**< Compressed horizontal and vertical curvature */
                uint32_t polyCurveRotation; /**< Compressed rotation start point */
};

/** Full detail unit shape with curved faces */
class MappedUnitShape final
{
                alignas(16) MappedUnitShapeCurve top; /**< Top face curvature */
                alignas(16) MappedUnitShapeCurve down; /**< Bottom face curvature */
                alignas(16) MappedUnitShapeCurve left; /**< Left face curvature */
                alignas(16) MappedUnitShapeCurve right; /**< Right face curvature */
                alignas(16) MappedUnitShapeCurve front; /**< Front face curvature */
                alignas(16) MappedUnitShapeCurve back; /**< Back face curvature */

                uint16_t polyCurveLTop; /**< Left face top edge */
                uint16_t polyCurveRTop; /**< Right face top edge */
                uint16_t polyCurveLDown; /**< Left face bottom edge */
                uint16_t polyCurveRDown; /**< Right face bottom edge */
                uint16_t polyCurveLRight; /**< Left face right edge */
                uint16_t polyCurveRLeft; /**< Right face left edge */
                uint16_t polyCurveLLeft; /**< Left face left edge */
                uint16_t polyCurveRRight; /**< Right face right edge */

                uint16_t width; /**< Unit width */
                uint16_t height; /**< Unit height */
                uint16_t depth; /**< Unit depth */
};

/** Medium detail unit shape with simplified curves */
class MappedUnitShapeMedium final
{
                alignas(8) uint32_t polyCurveRotation; /**< Shared rotation for all faces */
                uint16_t polyCurveHorizontal; /**< Shared horizontal curvature */
                uint16_t polyCurveVertical; /**< Shared vertical curvature */
                uint16_t width; /**< Unit width */
                uint16_t height; /**< Unit height */
                uint16_t depth; /**< Unit depth */
};

/** Low detail unit shape with no curves, basic cubic form */
class MappedUnitShapeLow final
{
                uint16_t width; /**< Unit width */
                uint16_t height; /**< Unit height */
                uint16_t depth; /**< Unit depth */
                uint8_t  visibleFaces; /**< Bitmask of visible faces: top(1), bottom(2),
                            left(4), right(8), front(16), back(32) */
};

/** Culled unit shape with only top face visible */
class MappedUnitShapeCulledTop final
{
                alignas(16) MappedUnitShapeCurve top; /**< Top face curvature */
                uint16_t width; /**< Unit width */
                uint16_t height; /**< Unit height */
                uint16_t depth; /**< Unit depth */
};

/** Culled unit shape with only side faces visible */
class MappedUnitShapeCulledSides final
{
                alignas(16) MappedUnitShapeCurve left; /**< Left face curvature */
                alignas(16) MappedUnitShapeCurve right; /**< Right face curvature */
                alignas(16) MappedUnitShapeCurve front; /**< Front face curvature */
                alignas(16) MappedUnitShapeCurve back; /**< Back face curvature */
                uint16_t width; /**< Unit width */
                uint16_t height; /**< Unit height */
                uint16_t depth; /**< Unit depth */
};

/** Culled unit shape with only bottom face visible */
class MappedUnitShapeCulledBottom final
{
                alignas(16) MappedUnitShapeCurve down; /**< Bottom face curvature */
                uint16_t width; /**< Unit width */
                uint16_t height; /**< Unit height */
                uint16_t depth; /**< Unit depth */
};

/** Level of detail for unit rendering */
enum class UnitLOD : uint8_t
{
        Full   = 0, /**< Full polygonal deformation with detailed curves */
        Medium = 1, /**< Simplified curves with reduced precision */
        Low    = 2, /**< Basic cubic shape without curves */
        Culled = 3 /**< Face culling optimization for hidden faces */
};

/** Compressed unit shape data (16 bytes total) */
struct CompressedUnitShape final
{
                uint32_t packedRotations; /**< 6 faces × 5 bits = 30 bits for rotation data */
                uint32_t packedCurvatures; /**< 6 faces × 5 bits = 30 bits for curvature planes */
                uint32_t packedEdges; /**< 6 edges × 4 bits = 24 bits for edge curves */
                uint32_t packedDimensions; /**< width (10 bits) | height (10 bits) | depth (10 bits)
                                              | padding (2 bits) */
};

/** Unit generated by GPU post-processing compute shaders */
struct PostUnit final
{
        public:
                enum class FlagBit
                {
                        SOLID   = 0x01,
                        VISIBLE = 0x02,
                        LIQUID  = 0x04
                };
                uint32_t
                    packedFlags; /**< lodLevel (8 bits) | flags (8 bits) | reserved (16 bits) */
                uint32_t            _padding; /**< Alignment padding for std430 */
                CompressedUnitShape shape; /**< Compressed shape data (16 bytes) */
                uint32_t _padding2[2]; /**< Additional padding to align to 32 bytes for std430 */
};

/** Maximum temperature value */
constexpr float maxTemperature = 1.0f;
/** Minimum temperature value */
constexpr float minTemperature = -1.0f;
/** Maximum moisture value */
constexpr float maxMoisture = 1.0f;
/** Minimum moisture value */
constexpr float minMoisture = 0.0f;
/** Maximum flammability value */
constexpr float maxFlammability = 64.0f;
/** Minimum flammability value */
constexpr float minFlamability = 0.0f;
/** Minimum equator distance value */
constexpr float minEquator = -1.0f;
/** Maximum equator distance value */
constexpr float maxEquator = 1.0f;
/** Maximum elevation value */
constexpr float maxElevation = 1.0f;
/** Minimum elevation value */
constexpr float minElevation = 0.0f;

class PreUnitRegistry;
/** Base class for unit types defined on CPU before world generation */
class PreUnit
{
                static std::unique_ptr<PreUnitRegistry> preUnitRegistry;

        public:
                using IType = uint32_t;
                using HType = uint64_t;

                /** Prop containing unit properties */
                struct Prop;
                /** Constructs a PreUnit with the given register
                 * @param unitRegister The unit register containing type information */
                explicit PreUnit(PreRegister unitRegister) noexcept;
                /** Virtual destructor */
                virtual ~PreUnit() noexcept = default;

                /** Checks if this unit can generate at the specified conditions
                 * @param elevation The elevation to check
                 * @param equator The equator distance to check
                 * @param moisture The moisture level to check
                 * @param temperature The temperature to check
                 * @return true if unit can generate, false otherwise */
                virtual bool canGenerateBy(float elevation,
                                           float equator,
                                           float moisture,
                                           float temperature) const;
                /** Returns the elevation tolerance for generation
                 * @return Maximum allowed elevation difference */
                virtual float getElevationNearAccept() const = 0;
                /** Returns the moisture tolerance for generation
                 * @return Maximum allowed moisture difference */
                virtual float getMoistureNearAccept() const = 0;
                /** Returns the equator distance tolerance for generation
                 * @return Maximum allowed equator distance difference */
                virtual float getEquatorNearAccept() const = 0;
                /** Returns the temperature tolerance for generation
                 * @return Maximum allowed temperature difference */
                virtual float getTemperatureNearAccept() const = 0;
                /** Checks if this unit can generate at the specified elevation
                 * @param elevation The elevation to check
                 * @return true if unit can generate, false otherwise */
                virtual bool canGenerateByElevation(float elevation) const;
                /** Checks if this unit can generate at the specified moisture
                 * @param moisture The moisture to check
                 * @return true if unit can generate, false otherwise */
                virtual bool canGenerateByMoisture(float moisture) const;
                /** Checks if this unit can generate at the specified equator distance
                 * @param equator The equator distance to check
                 * @return true if unit can generate, false otherwise */
                virtual bool canGenerateByEquator(float equator) const;
                /** Checks if this unit can generate at the specified temperature
                 * @param temperature The temperature to check
                 * @return true if unit can generate, false otherwise */
                virtual bool canGenerateByTemperature(float temperature) const;

                /** Returns the flammability value
                 * @return Flammability value */
                float getFlammability() const;
                /** Returns the explosion resistance value
                 * @return Explosion resistance value */
                float getExplosionResistance() const;
                /** Returns the minimum moisture for generation
                 * @return Minimum moisture value */
                float getMoistureStart() const;
                /** Returns the maximum moisture for generation
                 * @return Maximum moisture value */
                float getMoistureEnd() const;
                /** Returns the minimum equator distance for generation
                 * @return Minimum equator distance value */
                float getEquatorStart() const;
                /** Returns the maximum equator distance for generation
                 * @return Maximum equator distance value */
                float getEquatorEnd() const;
                /** Returns the minimum temperature for generation
                 * @return Minimum temperature value */
                float getTemperatureStart() const;
                /** Returns the maximum temperature for generation
                 * @return Maximum temperature value */
                float getTemperatureEnd() const;
                /** Returns the minimum elevation for generation
                 * @return Minimum elevation value */
                float getElevationStart() const;
                /** Returns the maximum elevation for generation
                 * @return Maximum elevation value */
                float getElevationEnd() const;
                /** Returns the unique type identifier
                 * @return Type ID */
                uint32_t getTypeId() const;
                /** Returns the unit hash
                 * @return Unit hash value */
                uint64_t getHash() const;

                /** Validates if the unit's properties are within acceptable ranges
                 * @return True if all properties are valid, false otherwise */
                bool validateProperties() const;
                /** Clamps temperature to valid range
                 * @param temperature Temperature value to clamp
                 * @return Clamped temperature value */
                static float clampTemperature(float temperature);
                /** Clamps moisture to valid range
                 * @param moisture Moisture value to clamp
                 * @return Clamped moisture value */
                static float clampMoisture(float moisture);
                /** Clamps equator distance to valid range
                 * @param equator Equator distance value to clamp
                 * @return Clamped equator distance value */
                static float clampEquator(float equator);
                /** Clamps elevation to valid range
                 * @param elevation Elevation value to clamp
                 * @return Clamped elevation value */
                static float clampElevation(float elevation);
                /** Clamps flammability to valid range
                 * @param flammability Flammability value to clamp
                 * @return Clamped flammability value */
                static float clampFlammability(float flammability);
                /** Clamps explosion resistance to valid range
                 * @param resistance Explosion resistance value to clamp
                 * @return Clamped explosion resistance value */
                static float clampExplosionResistance(float resistance);
                /** Checks if environmental conditions match unit generation requirements
                 * @param elevation Elevation to check
                 * @param equator Equator distance to check
                 * @param moisture Moisture to check
                 * @param temperature Temperature to check
                 * @return True if conditions match unit requirements */
                bool matchesRequirements(float elevation, float equator, float moisture,
                                        float temperature) const;
                /** Returns a string representation of the unit
                 * @return String representation */
                std::string toString() const;
                /** Sets the flammability value
                 * @param value The flammability value to set */
                void setFlammability(float value);
                /** Sets the explosion resistance value
                 * @param value The explosion resistance value to set */
                void setExplosionResistance(float value);
                /** Sets the minimum moisture for generation
                 * @param value The minimum moisture value */
                void setMoistureStart(float value);
                /** Sets the maximum moisture for generation
                 * @param value The maximum moisture value */
                void setMoistureEnd(float value);
                /** Sets the minimum temperature for generation
                 * @param value The minimum temperature value */
                void setTemperatureStart(float value);
                /** Sets the maximum temperature for generation
                 * @param value The maximum temperature value */
                void setTemperatureEnd(float value);
                /** Sets the minimum equator distance for generation
                 * @param value The minimum equator distance value */
                void setEquatorStart(float value);
                /** Sets the maximum equator distance for generation
                 * @param value The maximum equator distance value */
                void setEquatorEnd(float value);
                /** Sets the minimum elevation for generation
                 * @param value The minimum elevation value */
                void setElevationStart(float value);
                /** Sets the maximum elevation for generation
                 * @param value The maximum elevation value */
                void setElevationEnd(float value);

        protected:
                /** Sets the unique type identifier
                 * @param value The type ID to set */
                void setTypeId(uint32_t value);
                /** Sets the unit hash
                 * @param value The hash value to set */
                void setHash(uint64_t value);
        private:
                std::unique_ptr<Prop> prop;
};

/** Prop structure for PreUnit containing environmental and physical properties */
struct PreUnit::Prop
{
                float    flammability; /**< Flammability value */
                float    explosionResistance; /**< Explosion resistance value */
                float    moistureStart; /**< Minimum moisture for generation */
                float    moistureEnd; /**< Maximum moisture for generation */
                float    equatorStart; /**< Minimum equator distance for generation */
                float    equatorEnd; /**< Maximum equator distance for generation */
                float    temperatureStart; /**< Minimum temperature for generation */
                float    temperatureEnd; /**< Maximum temperature for generation */
                float    elevationStart; /**< Minimum elevation for generation */
                float    elevationEnd; /**< Maximum elevation for generation */
                uint32_t typeId; /**< Unique type identifier */
                uint64_t hash; /**< Unit hash value */
};

} // namespace rl

#endif
