file(READ ${INPUT_FILE} HEX_DATA HEX)
string(LENGTH "${HEX_DATA}" HEX_LENGTH)
math(EXPR BYTE_COUNT "${HEX_LENGTH} / 2")
math(EXPR UINT32_COUNT "${BYTE_COUNT} / 4")

string(REPLACE "_" ";" WORD_LIST "${VARIABLE_NAME}")
set(CAMELCASE_RESULT "")
set(IS_FIRST_WORD TRUE)
foreach(WORD IN LISTS WORD_LIST)
  string(LENGTH "${WORD}" WORD_LEN)
  set(HAS_INTERNAL_UPPERCASE FALSE)
  if(WORD_LEN GREATER 1)
    math(EXPR LAST_INDEX "${WORD_LEN} - 1")
    foreach(RANGE RANGE 1 ${LAST_INDEX})
      string(SUBSTRING "${WORD}" ${RANGE} 1 CHAR)
      string(TOLOWER "${CHAR}" CHAR_LOWER)
      if(NOT "${CHAR}" STREQUAL "${CHAR_LOWER}")
        set(HAS_INTERNAL_UPPERCASE TRUE)
        break()
      endif()
    endforeach()
  endif()
    
  if(IS_FIRST_WORD)
    string(TOLOWER "${WORD}" WORD_LOWER)
    string(APPEND CAMELCASE_RESULT "${WORD_LOWER}")
    set(IS_FIRST_WORD FALSE)
  else()
    # Subsequent words: PascalCase
    if(HAS_INTERNAL_UPPERCASE)
       string(SUBSTRING "${WORD}" 0  1 FIRST_LETTER)
       string(SUBSTRING "${WORD}" 1 -1 REST_WORD)
       string(TOUPPER "${FIRST_LETTER}" FIRST_LETTER_UP)
       string(APPEND CAMELCASE_RESULT "${FIRST_LETTER_UP}${REST_WORD}")
    else()
      string(TOLOWER "${WORD}" WORD_LOWER)
      string(SUBSTRING "${WORD_LOWER}" 0  1 FIRST_LETTER)
      string(SUBSTRING "${WORD_LOWER}" 1 -1 REST_WORD)
      string(TOUPPER "${FIRST_LETTER}" FIRST_LETTER_UP)
      string(APPEND CAMELCASE_RESULT "${FIRST_LETTER_UP}${REST_WORD}")
    endif()
  endif()
endforeach()
    
set(HEADER_CONTENT "#ifndef ${VARIABLE_NAME}_H\n")
set(HEADER_CONTENT "${HEADER_CONTENT}#define ${VARIABLE_NAME}_H\n\n")
set(HEADER_CONTENT "${HEADER_CONTENT}#include <cstdint>\n\n")
set(HEADER_CONTENT "${HEADER_CONTENT}extern const uint32_t ${CAMELCASE_RESULT}_size;\n")
set(HEADER_CONTENT "${HEADER_CONTENT}extern const uint32_t ${CAMELCASE_RESULT}_data[];\n\n")
set(HEADER_CONTENT "${HEADER_CONTENT}#endif // ${VARIABLE_NAME}_H\n")

file(WRITE ${OUTPUT_H} "${HEADER_CONTENT}")

get_filename_component(OUTPUT_H_FILENAME ${OUTPUT_H} NAME)
set(CFILE_CONTENT "#include \"${OUTPUT_H_FILENAME}\"\n\n")
set(CFILE_CONTENT "${CFILE_CONTENT}const uint32_t ${CAMELCASE_RESULT}_size = ${UINT32_COUNT};\n\n")
set(CFILE_CONTENT "${CFILE_CONTENT}const uint32_t ${CAMELCASE_RESULT}_data[] = {\n")

set(COUNT 0)
set(LINE "")
string(REGEX MATCHALL "........" HEX_UINT32S "${HEX_DATA}")
foreach(HEX_UINT32 IN LISTS HEX_UINT32S)
  string(SUBSTRING "${HEX_UINT32}" 6 2 BYTE3)
  string(SUBSTRING "${HEX_UINT32}" 4 2 BYTE2)
  string(SUBSTRING "${HEX_UINT32}" 2 2 BYTE1)
  string(SUBSTRING "${HEX_UINT32}" 0 2 BYTE0)
  set(LINE "${LINE} 0x${BYTE3}${BYTE2}${BYTE1}${BYTE0},")
  math(EXPR COUNT "${COUNT} + 1")
  
  if(COUNT EQUAL 4)
    set(CFILE_CONTENT "${CFILE_CONTENT}${LINE}\n")
    set(LINE "")
    set(COUNT 0)
  endif()
endforeach()

if(NOT "${LINE}" STREQUAL "")
  set(CFILE_CONTENT "${CFILE_CONTENT}${LINE}\n")
endif()

set(CFILE_CONTENT "${CFILE_CONTENT}};\n\n")

file(WRITE ${OUTPUT_C} "${CFILE_CONTENT}")
